name: Audit

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
          annotations: true
          min-severity: high

  Audit:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: Homebrew/actions/setup-homebrew@097625b28a26ba4b7437926ab03b4d3bd2e6c3d1 # master
      - name: Tap this repository
        run: |
          mkdir -p $(brew --repository)/Library/Taps/clouatre-labs
          ln -s $GITHUB_WORKSPACE $(brew --repository)/Library/Taps/clouatre-labs/homebrew-tap
      - name: Audit formulae
        run: brew audit --strict --online --tap clouatre-labs/tap
